### ISSUE TITLE
[Feature] FAQ与提问指南

### ISSUE THREAD

**Issue by HairlessVillager** [WHU-MSC/wiki#2]
在群里时常有人问一些重复的问题，这些问题的出现次数很多，并且在 wiki 上没有容易找到的指导。基于此提议加入FAQ。

有些问题并不完整，缺少必要的信息，使得其他愿意帮助的人需要反复交流才能解决问题。基于此提议加入提问指南。

如果这两部分内容完成，将大大提高群内解决新人问题的效率，同时也能在一定程度上培养新人的社区意识。

**Comment by liaosunny123** [comment]
你可以帮助完善这部分工作嘛

**Comment by HairlessVillager** [comment]
行，你要不给我指一下在哪弄？（这么久没上github果咩纳塞😭）

**Comment by liaosunny123** [comment]
@immengzi 来指个路

**Comment by immengzi** [comment]
@HairlessVillager docs/tech/beginners-guide/how-to-ask-questions-the-smart-way-extreme-version.md

**Comment by HairlessVillager** [comment]
Alright! 我会尽快完成这部分工作。

**Comment by immengzi** [comment]
> Alright! 我会尽快完成这部分工作。

感谢！

**Comment by HairlessVillager** [comment]
我已经写好了，也自查了一遍，你们看看有什么需要修改或者补充的，我一并加上去 @liaosunny123 @immengzi

**Comment by immengzi** [comment]
谢谢，你的工作对我们非常有用，它会帮助到很多初学者！ @HairlessVillager

**Comment by liaosunny123** [comment]
解决方法：利用 cd 命令切换到正确的 Git 仓库路径。

这一段需要增加上下文，例如如果是clone操作，那么可能需要 cd 到正确路径。如果是正常操作，检查是否 init 仓库了

**Comment by HairlessVillager** [comment]
> 解决方法：利用 cd 命令切换到正确的 Git 仓库路径。
> 
> 这一段需要增加上下文，例如如果是clone操作，那么可能需要 cd 到正确路径。如果是正常操作，检查是否 init 仓库了

可以补充上去。我当时只是看了群内的讨论，没有想这么多。

不过 pr 已经关了，我修改提交会再开一个 pr，要不你自己修改一下吧🥰
